package Presentation;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionListener;

public class Instructions extends JPanel {
    private JPanel InstructionsPanel;
    private JButton mainMenuButton;
    private JTextPane instructionsTextPane;

    public Instructions() {

    }

    public JPanel getInstructionsPanel() {
        return InstructionsPanel;
    }

    public JButton getMainMenuButton() {
        return mainMenuButton;
    }

    public void addMainMenuButtonActionListener(ActionListener listener) {
        mainMenuButton.addActionListener(listener);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        InstructionsPanel = new JPanel();
        InstructionsPanel.setLayout(new GridBagLayout());
        InstructionsPanel.setBackground(new Color(-12501697));
        InstructionsPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createRaisedBevelBorder(), "Mastermind", TitledBorder.CENTER, TitledBorder.BELOW_TOP, this.$$$getFont$$$("DejaVu Sans Mono", Font.BOLD | Font.ITALIC, 28, InstructionsPanel.getFont()), new Color(-4737097)));
        mainMenuButton = new JButton();
        mainMenuButton.setText("Back");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.SOUTHEAST;
        gbc.insets = new Insets(0, 0, 5, 5);
        InstructionsPanel.add(mainMenuButton, gbc);
        instructionsTextPane = new JTextPane();
        instructionsTextPane.setBackground(new Color(-12501697));
        instructionsTextPane.setEditable(false);
        instructionsTextPane.setForeground(new Color(-4737097));
        instructionsTextPane.setText("Aqui van les instruccions");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        InstructionsPanel.add(instructionsTextPane, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return InstructionsPanel;
    }
}
