package Presentation;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionListener;

public class Login {
    private JPanel LoginRegisterPanel;
    private JTabbedPane TabbedLoginRegister;
    private JPanel LoginPanel;
    private JPanel RegisterPanel;
    private JTextField usernameLogin;
    private JPasswordField passwordLogin;
    private JButton loginButton;
    private JTextField usernameRegister;
    private JPasswordField PasswordRegister;
    private JButton registerButton;
    private JLabel psLoginLabel;
    private JLabel usLoginLabel;
    private JLabel usRegLabel;
    private JLabel psRegLabel;

    public JPanel getLoginRegisterPanel() {
        return LoginRegisterPanel;
    }

    public JButton getLoginButton() {
        return loginButton;
    }

    public JButton getRegisterButton() {
        return registerButton;
    }

    public void addLoginButtonActionListener(ActionListener listener) {
        loginButton.addActionListener(listener);
    }

    public void addRegisterButtonActionListener(ActionListener listener) {
        registerButton.addActionListener(listener);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        LoginRegisterPanel = new JPanel();
        LoginRegisterPanel.setLayout(new BorderLayout(0, 0));
        LoginRegisterPanel.setBackground(new Color(-12501697));
        LoginRegisterPanel.setEnabled(true);
        LoginRegisterPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createRaisedBevelBorder(), "Mastermind", TitledBorder.CENTER, TitledBorder.BELOW_TOP, this.$$$getFont$$$("DejaVu Sans Mono", Font.BOLD | Font.ITALIC, 28, LoginRegisterPanel.getFont()), new Color(-4737097)));
        TabbedLoginRegister = new JTabbedPane();
        TabbedLoginRegister.setBackground(new Color(-12501697));
        TabbedLoginRegister.setForeground(new Color(-4737097));
        TabbedLoginRegister.setTabLayoutPolicy(0);
        TabbedLoginRegister.setTabPlacement(1);
        TabbedLoginRegister.setToolTipText("");
        LoginRegisterPanel.add(TabbedLoginRegister, BorderLayout.CENTER);
        LoginPanel = new JPanel();
        LoginPanel.setLayout(new GridBagLayout());
        LoginPanel.setBackground(new Color(-12501697));
        LoginPanel.setForeground(new Color(-12501697));
        LoginPanel.setToolTipText("");
        TabbedLoginRegister.addTab("Login", null, LoginPanel, "Login with your existing account");
        psLoginLabel = new JLabel();
        psLoginLabel.setForeground(new Color(-4737097));
        psLoginLabel.setText("Password");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 30, 0, 0);
        LoginPanel.add(psLoginLabel, gbc);
        passwordLogin = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 15, 0, 30);
        LoginPanel.add(passwordLogin, gbc);
        usLoginLabel = new JLabel();
        usLoginLabel.setForeground(new Color(-4737097));
        usLoginLabel.setText("Username");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 30, 0, 0);
        LoginPanel.add(usLoginLabel, gbc);
        usernameLogin = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 15, 0, 30);
        LoginPanel.add(usernameLogin, gbc);
        loginButton = new JButton();
        loginButton.setText("Login");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 30, 0, 0);
        LoginPanel.add(loginButton, gbc);
        RegisterPanel = new JPanel();
        RegisterPanel.setLayout(new GridBagLayout());
        RegisterPanel.setBackground(new Color(-12501697));
        TabbedLoginRegister.addTab("Register", null, RegisterPanel, "Register a new account");
        usRegLabel = new JLabel();
        usRegLabel.setForeground(new Color(-4737097));
        usRegLabel.setText("Username");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 30, 0, 0);
        RegisterPanel.add(usRegLabel, gbc);
        psRegLabel = new JLabel();
        psRegLabel.setForeground(new Color(-4737097));
        psRegLabel.setText("Password");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 30, 0, 0);
        RegisterPanel.add(psRegLabel, gbc);
        usernameRegister = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 15, 0, 30);
        RegisterPanel.add(usernameRegister, gbc);
        PasswordRegister = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 15, 0, 30);
        RegisterPanel.add(PasswordRegister, gbc);
        registerButton = new JButton();
        registerButton.setText("Register");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 14, 0, 0);
        RegisterPanel.add(registerButton, gbc);
        psLoginLabel.setLabelFor(passwordLogin);
        usLoginLabel.setLabelFor(usernameLogin);
        usRegLabel.setLabelFor(usernameRegister);
        psRegLabel.setLabelFor(PasswordRegister);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return LoginRegisterPanel;
    }
}
